-- both test users have the password "password"

-- USERS 
insert into users (username, password, first_name, last_name, email, skill) values ('mreckless0', 'uPCqp6ebHKS', 'Murdoch', 'Reckless', 'mreckless0@ed.gov', 'GIS Technical Architect');
insert into users (username, password, first_name, last_name, email, skill) values ('dpagel1', 'JK93WsgBroTu', 'Dareen', 'Pagel', 'dpagel1@behance.net', 'GIS Technical Architect');
insert into users (username, password, first_name, last_name, email, skill) values ('gblaxall2', 'Rs3tMk', 'Golda', 'Blaxall', 'gblaxall2@last.fm', 'Accounting Assistant IV');
insert into users (username, password, first_name, last_name, email, skill) values ('mdanson3', 'SZDpnjj', 'Melva', 'Danson', 'mdanson3@multiply.com', 'Food Chemist');
insert into users (username, password, first_name, last_name, email, skill) values ('gcandy4', 'gco25Bbuqh', 'Grace', 'Candy', 'gcandy4@opensource.org', 'Nurse');
insert into users (username, password, first_name, last_name, email, skill) values ('ofeeley5', 'tUKXiWRf0wle', 'Othelia', 'Feeley', 'ofeeley5@acquirethisname.com', 'Geologist IV');
insert into users (username, password, first_name, last_name, email, skill) values ('gcardenosa6', 'k9iyhXC7', 'Gordy', 'Cardenosa', 'gcardenosa6@so-net.ne.jp', 'Software Consultant');
insert into users (username, password, first_name, last_name, email, skill) values ('bdowner7', '5OYPQSG74AN', 'Bernhard', 'Downer', 'bdowner7@patch.com', 'Registered Nurse');
insert into users (username, password, first_name, last_name, email, skill) values ('kbeatens8', 'U1KnCf', 'Kellina', 'Beatens', 'kbeatens8@cisco.com', 'Account Coordinator');
insert into users (username, password, first_name, last_name, email, skill) values ('cspensley9', 'rsidehI', 'Cyrillus', 'Spensley', 'cspensley9@theglobeandmail.com', 'Environmental Tech');
insert into users (username, password, first_name, last_name, email, skill) values ('dstacea', 'UKZ0td', 'Donnie', 'Stace', 'dstacea@parallels.com', 'Nuclear Power Engineer');
insert into users (username, password, first_name, last_name, email, skill) values ('jjeramb', 'dVpb0skFs', 'Jim', 'Jeram', 'jjeramb@bbb.org', 'Human Resources Assistant III');
insert into users (username, password, first_name, last_name, email, skill) values ('tmcbridec', '3bNTTsf3', 'Tandi', 'McBride', 'tmcbridec@amazon.co.uk', 'Senior Cost Accountant');
insert into users (username, password, first_name, last_name, email, skill) values ('lbutlandd', 'urD1me19', 'Lise', 'Butland', 'lbutlandd@webmd.com', 'Accounting Assistant II');
insert into users (username, password, first_name, last_name, email, skill) values ('mgrebbine', '0BdSRS3AU6MM', 'Milt', 'Grebbin', 'mgrebbine@mapy.cz', 'Human Resources Manager');
insert into users (username, password, first_name, last_name, email, skill) values ('yhardmanf', 'nh7Hh0aL', 'Yancey', 'Hardman', 'yhardmanf@google.com.au', 'VP Marketing');
insert into users (username, password, first_name, last_name, email, skill) values ('cjaxong', 'Hv4fRYm7', 'Craggy', 'Jaxon', 'cjaxong@dmoz.org', 'VP Accounting');
insert into users (username, password, first_name, last_name, email, skill) values ('jgoverh', 'zCvEOsDU8', 'Jarret', 'Gover', 'jgoverh@nytimes.com', 'Web Developer I');
insert into users (username, password, first_name, last_name, email, skill) values ('cileyi', 'wWsZ2ehLaWSi', 'Caralie', 'Iley', 'cileyi@desdev.cn', 'VP Sales');
insert into users (username, password, first_name, last_name, email, skill) values ('gbadseyj', 'lsGdkZkNKJ', 'Gasper', 'Badsey', 'gbadseyj@multiply.com', 'Occupational Therapist');


-- COMPANIES 

insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('pulvinar', '0qZfxu5Mamy', 'Bubbletube', 'Philippines', 579, 'fermentum justo nec condimentum neque', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://uol.com.br/erat/tortor/sollicitudin/mi.jsp?magna=sollicitudin&vulputate=vitae&luctus=consectetuer&cum=eget&sociis=rutrum&natoque=at&penatibus=lorem&et=integer&magnis=tincidunt&dis=ante&parturient=vel&montes=ipsum&nascetur=praesent&ridiculus=blandit&mus=lacinia&vivamus=erat&vestibulum=vestibulum&sagittis=sed&sapien=magna&cum=at&sociis=nunc', 'http://dummyimage.com/150x150.png/dddddd/000000', 'http://dummyimage.com/800x140.png/5fa2dd/ffffff', 'Senior Quality Engineer');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('congue', 'zftmsYB3liEh', 'Divape', 'China', 633, 'nibh fusce lacus purus aliquet', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://bandcamp.com/neque/sapien/placerat/ante.xml?lobortis=habitasse&est=platea&phasellus=dictumst&sit=aliquam&amet=augue&erat=quam&nulla=sollicitudin&tempus=vitae&vivamus=consectetuer&in=eget&felis=rutrum&eu=at&sapien=lorem&cursus=integer&vestibulum=tincidunt&proin=ante&eu=vel&mi=ipsum&nulla=praesent&ac=blandit&enim=lacinia&in=erat&tempor=vestibulum&turpis=sed&nec=magna&euismod=at&scelerisque=nunc&quam=commodo&turpis=placerat&adipiscing=praesent&lorem=blandit&vitae=nam&mattis=nulla&nibh=integer&ligula=pede&nec=justo&sem=lacinia&duis=eget&aliquam=tincidunt&convallis=eget&nunc=tempus&proin=vel&at=pede&turpis=morbi&a=porttitor&pede=lorem&posuere=id&nonummy=ligula&integer=suspendisse', 'http://dummyimage.com/150x150.png/dddddd/000000', 'http://dummyimage.com/800x140.png/cc0000/ffffff', 'Developer III');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('consequat', '8w59gA', 'Mymm', 'Thailand', 911, 'felis donec semper sapien a', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'https://cbc.ca/at.jsp?quam=lectus&suspendisse=vestibulum&potenti=quam&nullam=sapien&porttitor=varius&lacus=ut&at=blandit&turpis=non&donec=interdum&posuere=in&metus=ante&vitae=vestibulum&ipsum=ante&aliquam=ipsum&non=primis&mauris=in&morbi=faucibus&non=orci&lectus=luctus&aliquam=et&sit=ultrices&amet=posuere&diam=cubilia&in=curae&magna=duis&bibendum=faucibus&imperdiet=accumsan&nullam=odio&orci=curabitur&pede=convallis&venenatis=duis&non=consequat&sodales=dui&sed=nec&tincidunt=nisi', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'Accountant IV');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('ridiculus', 'pKILKvny2', 'Realcube', 'Indonesia', 213, 'lacus at turpis donec posuere', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://state.gov/libero.html?metus=ultrices&vitae=phasellus&ipsum=id&aliquam=sapien&non=in&mauris=sapien&morbi=iaculis&non=congue&lectus=vivamus&aliquam=metus&sit=arcu&amet=adipiscing&diam=molestie&in=hendrerit&magna=at&bibendum=vulputate&imperdiet=vitae&nullam=nisl&orci=aenean&pede=lectus&venenatis=pellentesque&non=eget&sodales=nunc&sed=donec&tincidunt=quis&eu=orci&felis=eget&fusce=orci&posuere=vehicula&felis=condimentum&sed=curabitur&lacus=in&morbi=libero&sem=ut&mauris=massa&laoreet=volutpat&ut=convallis&rhoncus=morbi&aliquet=odio&pulvinar=odio&sed=elementum&nisl=eu&nunc=interdum&rhoncus=eu&dui=tincidunt&vel=in&sem=leo&sed=maecenas&sagittis=pulvinar&nam=lobortis&congue=est&risus=phasellus&semper=sit&porta=amet&volutpat=erat&quam=nulla&pede=tempus&lobortis=vivamus&ligula=in&sit=felis&amet=eu&eleifend=sapien&pede=cursus&libero=vestibulum&quis=proin&orci=eu&nullam=mi&molestie=nulla&nibh=ac&in=enim&lectus=in&pellentesque=tempor&at=turpis&nulla=nec&suspendisse=euismod&potenti=scelerisque&cras=quam&in=turpis&purus=adipiscing&eu=lorem&magna=vitae&vulputate=mattis&luctus=nibh&cum=ligula&sociis=nec&natoque=sem', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/cc0000/ffffff', 'Staff Accountant III');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('integer', '6fEvyoEZdD', 'Oyope', 'Cambodia', 657, 'tortor sollicitudin mi sit', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'https://naver.com/lorem/ipsum/dolor/sit.html?ornare=lectus&consequat=pellentesque&lectus=eget&in=nunc&est=donec&risus=quis&auctor=orci&sed=eget&tristique=orci&in=vehicula&tempus=condimentum&sit=curabitur&amet=in&sem=libero&fusce=ut&consequat=massa&nulla=volutpat&nisl=convallis&nunc=morbi', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/5fa2dd/ffffff', 'Payment Adjustment Coordinator');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('erat', 'XeOse5zLlM', 'Twitterworks', 'Bulgaria', 152, 'integer non velit donec', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'https://umn.edu/aenean/lectus/pellentesque.jpg?justo=leo&eu=maecenas&massa=pulvinar&donec=lobortis&dapibus=est&duis=phasellus&at=sit&velit=amet&eu=erat&est=nulla', 'http://dummyimage.com/150x150.png/cc0000/ffffff', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'Tax Accountant');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('parturient', 'SFGixc9p', 'Edgewire', 'Ukraine', 581, 'pharetra magna ac consequat metus sapien', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'https://webs.com/id/turpis/integer/aliquet/massa/id/lobortis.html?sed=nunc&magna=rhoncus&at=dui&nunc=vel&commodo=sem&placerat=sed&praesent=sagittis&blandit=nam&nam=congue&nulla=risus&integer=semper&pede=porta&justo=volutpat&lacinia=quam&eget=pede&tincidunt=lobortis&eget=ligula&tempus=sit&vel=amet&pede=eleifend&morbi=pede&porttitor=libero&lorem=quis&id=orci&ligula=nullam&suspendisse=molestie&ornare=nibh&consequat=in&lectus=lectus&in=pellentesque&est=at&risus=nulla&auctor=suspendisse&sed=potenti&tristique=cras&in=in&tempus=purus&sit=eu&amet=magna&sem=vulputate&fusce=luctus&consequat=cum&nulla=sociis&nisl=natoque&nunc=penatibus&nisl=et&duis=magnis&bibendum=dis&felis=parturient&sed=montes&interdum=nascetur&venenatis=ridiculus&turpis=mus&enim=vivamus&blandit=vestibulum&mi=sagittis&in=sapien&porttitor=cum&pede=sociis&justo=natoque&eu=penatibus&massa=et&donec=magnis&dapibus=dis&duis=parturient&at=montes&velit=nascetur&eu=ridiculus&est=mus&congue=etiam&elementum=vel&in=augue&hac=vestibulum&habitasse=rutrum&platea=rutrum&dictumst=neque&morbi=aenean&vestibulum=auctor&velit=gravida&id=sem&pretium=praesent&iaculis=id&diam=massa&erat=id&fermentum=nisl&justo=venenatis&nec=lacinia', 'http://dummyimage.com/150x150.png/5fa2dd/ffffff', 'http://dummyimage.com/800x140.png/cc0000/ffffff', 'Assistant Manager');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('ligula', 'uGVbP0YUEreW', 'Trilia', 'China', 225, 'massa tempor convallis nulla neque libero', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://wsj.com/curabitur/convallis/duis/consequat.html?consequat=dictumst&nulla=etiam&nisl=faucibus&nunc=cursus&nisl=urna&duis=ut&bibendum=tellus&felis=nulla&sed=ut&interdum=erat&venenatis=id&turpis=mauris&enim=vulputate&blandit=elementum&mi=nullam&in=varius&porttitor=nulla&pede=facilisi&justo=cras&eu=non&massa=velit&donec=nec&dapibus=nisi&duis=vulputate&at=nonummy&velit=maecenas&eu=tincidunt&est=lacus', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'Assistant Media Planner');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('sed', 'cf0QBd', 'Ozu', 'Ecuador', 448, 'id lobortis convallis tortor', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'https://epa.gov/porta/volutpat/quam/pede/lobortis/ligula/sit.xml?urna=eros&ut=suspendisse&tellus=accumsan&nulla=tortor&ut=quis&erat=turpis&id=sed&mauris=ante&vulputate=vivamus&elementum=tortor&nullam=duis&varius=mattis&nulla=egestas&facilisi=metus&cras=aenean&non=fermentum&velit=donec&nec=ut&nisi=mauris&vulputate=eget&nonummy=massa&maecenas=tempor&tincidunt=convallis&lacus=nulla&at=neque&velit=libero&vivamus=convallis&vel=eget&nulla=eleifend&eget=luctus&eros=ultricies&elementum=eu&pellentesque=nibh&quisque=quisque&porta=id&volutpat=justo', 'http://dummyimage.com/150x150.png/cc0000/ffffff', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'GIS Technical Architect');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('nulla', 'RskZXCqmbb', 'Photojam', 'Egypt', 463, 'mauris eget massa tempor convallis', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'https://reuters.com/mollis/molestie/lorem/quisque/ut.json?nulla=habitasse&nunc=platea&purus=dictumst&phasellus=etiam&in=faucibus&felis=cursus&donec=urna&semper=ut&sapien=tellus&a=nulla&libero=ut&nam=erat&dui=id&proin=mauris&leo=vulputate&odio=elementum&porttitor=nullam&id=varius&consequat=nulla&in=facilisi&consequat=cras&ut=non&nulla=velit&sed=nec&accumsan=nisi&felis=vulputate&ut=nonummy&at=maecenas&dolor=tincidunt&quis=lacus&odio=at&consequat=velit&varius=vivamus&integer=vel&ac=nulla&leo=eget&pellentesque=eros&ultrices=elementum&mattis=pellentesque&odio=quisque&donec=porta&vitae=volutpat&nisi=erat&nam=quisque&ultrices=erat&libero=eros&non=viverra&mattis=eget&pulvinar=congue&nulla=eget&pede=semper&ullamcorper=rutrum&augue=nulla&a=nunc&suscipit=purus&nulla=phasellus&elit=in&ac=felis&nulla=donec&sed=semper&vel=sapien&enim=a&sit=libero&amet=nam&nunc=dui&viverra=proin&dapibus=leo&nulla=odio&suscipit=porttitor&ligula=id&in=consequat&lacus=in&curabitur=consequat&at=ut&ipsum=nulla&ac=sed&tellus=accumsan&semper=felis&interdum=ut&mauris=at&ullamcorper=dolor&purus=quis&sit=odio&amet=consequat&nulla=varius&quisque=integer&arcu=ac&libero=leo&rutrum=pellentesque&ac=ultrices&lobortis=mattis&vel=odio&dapibus=donec&at=vitae', 'http://dummyimage.com/150x150.png/cc0000/ffffff', 'http://dummyimage.com/800x140.png/dddddd/000000', 'Financial Advisor');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('at', 'LdkD6Bj', 'Oyoyo', 'Peru', 469, 'viverra pede ac diam', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'https://wordpress.com/in.json?ante=vel&nulla=sem&justo=sed&aliquam=sagittis&quis=nam&turpis=congue&eget=risus&elit=semper&sodales=porta&scelerisque=volutpat&mauris=quam&sit=pede&amet=lobortis&eros=ligula&suspendisse=sit&accumsan=amet&tortor=eleifend&quis=pede&turpis=libero&sed=quis&ante=orci&vivamus=nullam&tortor=molestie&duis=nibh&mattis=in&egestas=lectus&metus=pellentesque&aenean=at&fermentum=nulla&donec=suspendisse&ut=potenti&mauris=cras&eget=in&massa=purus&tempor=eu&convallis=magna&nulla=vulputate&neque=luctus&libero=cum&convallis=sociis&eget=natoque&eleifend=penatibus&luctus=et&ultricies=magnis&eu=dis&nibh=parturient&quisque=montes&id=nascetur&justo=ridiculus&sit=mus&amet=vivamus&sapien=vestibulum&dignissim=sagittis&vestibulum=sapien&vestibulum=cum&ante=sociis&ipsum=natoque&primis=penatibus&in=et&faucibus=magnis&orci=dis&luctus=parturient&et=montes&ultrices=nascetur&posuere=ridiculus', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/5fa2dd/ffffff', 'Clinical Specialist');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('tincidunt', 'ovAGBbIodNAb', 'BlogXS', 'Poland', 550, 'eros suspendisse accumsan tortor quis', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://php.net/nunc/proin/at/turpis/a.xml?pede=pellentesque&ac=at&diam=nulla&cras=suspendisse&pellentesque=potenti&volutpat=cras&dui=in&maecenas=purus&tristique=eu&est=magna&et=vulputate&tempus=luctus&semper=cum&est=sociis&quam=natoque', 'http://dummyimage.com/150x150.png/cc0000/ffffff', 'http://dummyimage.com/800x140.png/dddddd/000000', 'Clinical Specialist');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('rhoncus', 'IeTiZHm5QM', 'Devpulse', 'Thailand', 294, 'est donec odio justo', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://hao123.com/non/interdum/in/ante/vestibulum.xml?lorem=sem&id=praesent&ligula=id&suspendisse=massa&ornare=id&consequat=nisl&lectus=venenatis&in=lacinia&est=aenean&risus=sit&auctor=amet&sed=justo', 'http://dummyimage.com/150x150.png/dddddd/000000', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'Geological Engineer');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('est', '4kESWSv50Uz', 'Wordware', 'China', 733, 'consectetuer adipiscing elit proin risus', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'https://wired.com/leo.js?etiam=faucibus&pretium=orci&iaculis=luctus&justo=et&in=ultrices&hac=posuere&habitasse=cubilia&platea=curae&dictumst=donec&etiam=pharetra&faucibus=magna&cursus=vestibulum&urna=aliquet&ut=ultrices&tellus=erat&nulla=tortor&ut=sollicitudin&erat=mi&id=sit&mauris=amet&vulputate=lobortis&elementum=sapien&nullam=sapien&varius=non&nulla=mi&facilisi=integer&cras=ac&non=neque&velit=duis&nec=bibendum&nisi=morbi&vulputate=non&nonummy=quam&maecenas=nec&tincidunt=dui&lacus=luctus&at=rutrum&velit=nulla&vivamus=tellus&vel=in&nulla=sagittis&eget=dui&eros=vel&elementum=nisl&pellentesque=duis&quisque=ac&porta=nibh&volutpat=fusce&erat=lacus&quisque=purus&erat=aliquet&eros=at&viverra=feugiat&eget=non&congue=pretium&eget=quis&semper=lectus&rutrum=suspendisse&nulla=potenti&nunc=in&purus=eleifend&phasellus=quam&in=a&felis=odio&donec=in&semper=hac&sapien=habitasse&a=platea&libero=dictumst&nam=maecenas&dui=ut', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'Help Desk Technician');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('scelerisque', 'rBE73l7y', 'Kwinu', 'Peru', 640, 'curabitur at ipsum ac tellus semper', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'https://census.gov/suspendisse/accumsan/tortor/quis/turpis/sed/ante.png?molestie=in&hendrerit=libero&at=ut&vulputate=massa&vitae=volutpat&nisl=convallis&aenean=morbi&lectus=odio&pellentesque=odio&eget=elementum&nunc=eu&donec=interdum&quis=eu&orci=tincidunt&eget=in&orci=leo&vehicula=maecenas&condimentum=pulvinar&curabitur=lobortis&in=est&libero=phasellus&ut=sit&massa=amet&volutpat=erat&convallis=nulla&morbi=tempus&odio=vivamus&odio=in&elementum=felis&eu=eu&interdum=sapien&eu=cursus&tincidunt=vestibulum&in=proin&leo=eu&maecenas=mi&pulvinar=nulla&lobortis=ac&est=enim&phasellus=in&sit=tempor&amet=turpis&erat=nec&nulla=euismod&tempus=scelerisque&vivamus=quam&in=turpis&felis=adipiscing&eu=lorem&sapien=vitae&cursus=mattis&vestibulum=nibh&proin=ligula&eu=nec&mi=sem&nulla=duis&ac=aliquam&enim=convallis&in=nunc&tempor=proin&turpis=at&nec=turpis&euismod=a&scelerisque=pede&quam=posuere&turpis=nonummy&adipiscing=integer&lorem=non&vitae=velit&mattis=donec&nibh=diam&ligula=neque&nec=vestibulum', 'http://dummyimage.com/150x150.png/cc0000/ffffff', 'http://dummyimage.com/800x140.png/cc0000/ffffff', 'Nurse Practicioner');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('sapien', 'f4hcAd2', 'Zoomcast', 'Kazakhstan', 775, 'turpis elementum ligula vehicula consequat morbi', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://cnbc.com/hac/habitasse.jsp?vulputate=ligula&nonummy=nec&maecenas=sem&tincidunt=duis&lacus=aliquam&at=convallis&velit=nunc&vivamus=proin&vel=at&nulla=turpis&eget=a&eros=pede&elementum=posuere&pellentesque=nonummy&quisque=integer&porta=non&volutpat=velit&erat=donec&quisque=diam&erat=neque&eros=vestibulum&viverra=eget&eget=vulputate&congue=ut&eget=ultrices&semper=vel&rutrum=augue&nulla=vestibulum&nunc=ante&purus=ipsum&phasellus=primis', 'http://dummyimage.com/150x150.png/5fa2dd/ffffff', 'http://dummyimage.com/800x140.png/cc0000/ffffff', 'Software Engineer III');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('lectus', 'AbkeA8B', 'Vipe', 'Brazil', 997, 'orci pede venenatis non sodales sed', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'https://oracle.com/diam.jsp?vulputate=porta&justo=volutpat&in=quam&blandit=pede&ultrices=lobortis&enim=ligula&lorem=sit&ipsum=amet&dolor=eleifend&sit=pede&amet=libero&consectetuer=quis&adipiscing=orci&elit=nullam&proin=molestie&interdum=nibh&mauris=in&non=lectus&ligula=pellentesque&pellentesque=at&ultrices=nulla&phasellus=suspendisse&id=potenti&sapien=cras&in=in', 'http://dummyimage.com/150x150.png/dddddd/000000', 'http://dummyimage.com/800x140.png/dddddd/000000', 'Structural Analysis Engineer');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('et', 'HeDERgn', 'Feedfish', 'Philippines', 610, 'suspendisse potenti in eleifend quam', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'https://seattletimes.com/convallis/tortor.js?convallis=molestie&morbi=lorem&odio=quisque&odio=ut&elementum=erat&eu=curabitur&interdum=gravida&eu=nisi&tincidunt=at&in=nibh&leo=in&maecenas=hac&pulvinar=habitasse&lobortis=platea&est=dictumst&phasellus=aliquam&sit=augue&amet=quam&erat=sollicitudin&nulla=vitae&tempus=consectetuer&vivamus=eget&in=rutrum&felis=at&eu=lorem&sapien=integer&cursus=tincidunt&vestibulum=ante&proin=vel&eu=ipsum&mi=praesent&nulla=blandit&ac=lacinia&enim=erat&in=vestibulum&tempor=sed&turpis=magna&nec=at&euismod=nunc&scelerisque=commodo&quam=placerat&turpis=praesent&adipiscing=blandit&lorem=nam&vitae=nulla&mattis=integer&nibh=pede&ligula=justo&nec=lacinia&sem=eget&duis=tincidunt&aliquam=eget', 'http://dummyimage.com/150x150.png/cc0000/ffffff', 'http://dummyimage.com/800x140.png/dddddd/000000', 'Account Coordinator');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('posuere', 'DcIgjOW7w6S4', 'Brainlounge', 'China', 343, 'consectetuer adipiscing elit proin risus', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'https://sina.com.cn/vitae/ipsum/aliquam.jpg?faucibus=justo&accumsan=nec&odio=condimentum&curabitur=neque&convallis=sapien&duis=placerat&consequat=ante&dui=nulla&nec=justo&nisi=aliquam&volutpat=quis&eleifend=turpis&donec=eget&ut=elit&dolor=sodales&morbi=scelerisque&vel=mauris&lectus=sit&in=amet&quam=eros&fringilla=suspendisse&rhoncus=accumsan&mauris=tortor&enim=quis&leo=turpis&rhoncus=sed&sed=ante&vestibulum=vivamus&sit=tortor&amet=duis&cursus=mattis&id=egestas&turpis=metus&integer=aenean&aliquet=fermentum&massa=donec&id=ut&lobortis=mauris&convallis=eget&tortor=massa&risus=tempor&dapibus=convallis&augue=nulla&vel=neque&accumsan=libero&tellus=convallis&nisi=eget&eu=eleifend&orci=luctus&mauris=ultricies&lacinia=eu&sapien=nibh&quis=quisque&libero=id&nullam=justo&sit=sit&amet=amet&turpis=sapien&elementum=dignissim&ligula=vestibulum&vehicula=vestibulum&consequat=ante&morbi=ipsum&a=primis&ipsum=in&integer=faucibus&a=orci&nibh=luctus&in=et&quis=ultrices&justo=posuere&maecenas=cubilia&rhoncus=curae&aliquam=nulla&lacus=dapibus&morbi=dolor&quis=vel&tortor=est', 'http://dummyimage.com/150x150.png/5fa2dd/ffffff', 'http://dummyimage.com/800x140.png/ff4444/ffffff', 'Biostatistician IV');
insert into companies (company_handle, password, company_name, country, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for) values ('viverra', '89WW7f7RJaQ2', 'Chatterpoint', 'Argentina', 297, 'in felis donec semper sapien', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'https://mediafire.com/quis/lectus/suspendisse/potenti.png?volutpat=interdum&erat=eu&quisque=tincidunt&erat=in&eros=leo&viverra=maecenas&eget=pulvinar&congue=lobortis&eget=est&semper=phasellus&rutrum=sit&nulla=amet&nunc=erat&purus=nulla&phasellus=tempus&in=vivamus&felis=in&donec=felis&semper=eu&sapien=sapien&a=cursus&libero=vestibulum&nam=proin&dui=eu&proin=mi&leo=nulla&odio=ac&porttitor=enim&id=in&consequat=tempor&in=turpis&consequat=nec&ut=euismod&nulla=scelerisque&sed=quam&accumsan=turpis&felis=adipiscing&ut=lorem&at=vitae&dolor=mattis&quis=nibh&odio=ligula&consequat=nec&varius=sem&integer=duis&ac=aliquam&leo=convallis&pellentesque=nunc&ultrices=proin&mattis=at&odio=turpis&donec=a&vitae=pede&nisi=posuere&nam=nonummy&ultrices=integer&libero=non&non=velit', 'http://dummyimage.com/150x150.png/ff4444/ffffff', 'http://dummyimage.com/800x140.png/dddddd/000000', 'Software Engineer I');