-- both test users have the password "password"

-- USERS 
insert into users (username, password, first_name, last_name, email, skill, role) values ('jwalwood0', 'g5upo7o', 'Jess', 'Walwood', 'jwalwood0@paypal.com', 'Junior Executive', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('acucuzza1', 'SiS7E4q3xHs', 'Adolph', 'Cucuzza', 'acucuzza1@cam.ac.uk', 'Nurse', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('hziems2', 'cf0W8X', 'Heywood', 'Ziems', 'hziems2@google.it', 'Database Administrator IV', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('rmilmith3', 'FTaibAz8n', 'Ralph', 'Milmith', 'rmilmith3@dyndns.org', 'Quality Engineer', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('iagass4', 'fT3I4thJxTH', 'Iorgos', 'Agass', 'iagass4@businesswire.com', 'Geological Engineer', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('bslide5', 'ZzMw6h1g3', 'Beret', 'Slide', 'bslide5@ox.ac.uk', 'Web Designer II', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('gbarnes6', 'T5F67qhhE', 'Greg', 'Barnes', 'gbarnes6@sitemeter.com', 'Senior Sales Associate', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('aladel7', 'P5Vcr9bODR', 'Ammamaria', 'Ladel', 'aladel7@prweb.com', 'Senior Sales Associate', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('adewes8', 'jMTiKsObMJBJ', 'Allin', 'Dewes', 'adewes8@auda.org.au', 'VP Product Management', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('sbachelar9', 'tlwSj8f', 'Sofia', 'Bachelar', 'sbachelar9@toplist.cz', 'Programmer I', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('centerleina', 'MWq5BsnPi', 'Carie', 'Enterlein', 'centerleina@networksolutions.com', 'Community Outreach Specialist', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('centerleb', '9dDW221XLOj', 'Cobby', 'Enterle', 'centerleb@howstuffworks.com', 'Nurse Practicioner', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('lmacconnalc', '5RSxmsT7BKT', 'Lodovico', 'MacConnal', 'lmacconnalc@apache.org', 'Engineer III', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('ldingled', 'TQYhiRoJvS', 'Lanny', 'Dingle', 'ldingled@boston.com', 'Financial Analyst', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('wcheyennee', 'YluzqcZpM', 'Whit', 'Cheyenne', 'wcheyennee@geocities.jp', 'Senior Developer', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('mrabjohnsf', 'kYy7EnwSQzai', 'Maison', 'Rabjohns', 'mrabjohnsf@diigo.com', 'Occupational Therapist', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('smilborng', 'QFnkHkVAnvLJ', 'Salvador', 'Milborn', 'smilborng@state.gov', 'Research Assistant II', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('gmouatth', 'Ng1oPlg', 'Guthrey', 'Mouatt', 'gmouatth@google.com.br', 'Media Manager I', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('bbesselli', 'DgAqtMbA', 'Bidget', 'Bessell', 'bbesselli@gravatar.com', 'Statistician III', 'user');
insert into users (username, password, first_name, last_name, email, skill, role) values ('skeej', 'VdDl8six7', 'Shay', 'Kee', 'skeej@paypal.com', 'Food Chemist', 'user');


-- COMPANIES 

insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('gsut', 'yyBcv6WnyX', 'Bogan LLC', 'Texas', 192, 'vitae nisi nam ultrices', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'https://networksolutions.com/scelerisque.jsp?porta=lacinia&volutpat=nisi&erat=venenatis&quisque=tristique&erat=fusce&eros=congue&viverra=diam&eget=id&congue=ornare&eget=imperdiet&semper=sapien&rutrum=urna&nulla=pretium&nunc=nisl&purus=ut&phasellus=volutpat&in=sapien&felis=arcu&donec=sed&semper=augue&sapien=aliquam&a=erat&libero=volutpat&nam=in&dui=congue&proin=etiam&leo=justo&odio=etiam&porttitor=pretium&id=iaculis&consequat=justo&in=in&consequat=hac&ut=habitasse&nulla=platea&sed=dictumst&accumsan=etiam&felis=faucibus&ut=cursus&at=urna&dolor=ut&quis=tellus&odio=nulla&consequat=ut&varius=erat&integer=id&ac=mauris&leo=vulputate&pellentesque=elementum&ultrices=nullam&mattis=varius&odio=nulla&donec=facilisi&vitae=cras&nisi=non&nam=velit', 'http://dummyimage.com/112x100.png/ff4444/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Occupational Therapist', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('usap', 'KvDcNv', 'Larson-Luettgen', 'Colorado', 266, 'nec dui luctus rutrum', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'https://discuz.net/lacinia.js?a=nulla&ipsum=justo&integer=aliquam&a=quis&nibh=turpis&in=eget&quis=elit&justo=sodales&maecenas=scelerisque&rhoncus=mauris&aliquam=sit&lacus=amet&morbi=eros&quis=suspendisse&tortor=accumsan&id=tortor&nulla=quis&ultrices=turpis', 'http://dummyimage.com/195x100.png/dddddd/000000', 'http://dummyimage.com/x.png/dddddd/000000', 'Database Administrator IV', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('gogl', 'EUc3WomzHlbz', 'Runolfsson-Wyman', 'Oregon', 792, 'viverra eget congue eget', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'https://symantec.com/aliquam/erat/volutpat/in/congue.json?at=in&nulla=tempor&suspendisse=turpis&potenti=nec&cras=euismod&in=scelerisque&purus=quam&eu=turpis&magna=adipiscing&vulputate=lorem&luctus=vitae&cum=mattis&sociis=nibh&natoque=ligula&penatibus=nec&et=sem&magnis=duis&dis=aliquam&parturient=convallis&montes=nunc&nascetur=proin&ridiculus=at&mus=turpis&vivamus=a&vestibulum=pede&sagittis=posuere&sapien=nonummy&cum=integer&sociis=non&natoque=velit&penatibus=donec&et=diam&magnis=neque&dis=vestibulum&parturient=eget&montes=vulputate&nascetur=ut&ridiculus=ultrices&mus=vel&etiam=augue&vel=vestibulum&augue=ante&vestibulum=ipsum&rutrum=primis&rutrum=in&neque=faucibus', 'http://dummyimage.com/147x100.png/dddddd/000000', 'http://dummyimage.com/x.png/dddddd/000000', 'Marketing Manager', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('mict', 'iTYnwHQ48tPv', 'Hammes-Kassulke', 'Arizona', 188, 'nec nisi volutpat eleifend donec', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'https://skype.com/velit/eu/est/congue.html?mus=luctus&vivamus=et&vestibulum=ultrices&sagittis=posuere&sapien=cubilia&cum=curae&sociis=mauris&natoque=viverra&penatibus=diam&et=vitae&magnis=quam&dis=suspendisse&parturient=potenti&montes=nullam&nascetur=porttitor&ridiculus=lacus&mus=at&etiam=turpis&vel=donec&augue=posuere&vestibulum=metus&rutrum=vitae&rutrum=ipsum&neque=aliquam&aenean=non&auctor=mauris&gravida=morbi&sem=non&praesent=lectus&id=aliquam&massa=sit&id=amet&nisl=diam&venenatis=in&lacinia=magna&aenean=bibendum&sit=imperdiet&amet=nullam&justo=orci&morbi=pede&ut=venenatis&odio=non&cras=sodales&mi=sed&pede=tincidunt&malesuada=eu&in=felis&imperdiet=fusce&et=posuere&commodo=felis&vulputate=sed&justo=lacus&in=morbi&blandit=sem&ultrices=mauris&enim=laoreet&lorem=ut&ipsum=rhoncus&dolor=aliquet&sit=pulvinar&amet=sed&consectetuer=nisl&adipiscing=nunc&elit=rhoncus&proin=dui&interdum=vel&mauris=sem&non=sed&ligula=sagittis&pellentesque=nam&ultrices=congue&phasellus=risus&id=semper&sapien=porta&in=volutpat&sapien=quam&iaculis=pede&congue=lobortis&vivamus=ligula&metus=sit&arcu=amet&adipiscing=eleifend&molestie=pede&hendrerit=libero&at=quis&vulputate=orci&vitae=nullam&nisl=molestie&aenean=nibh&lectus=in&pellentesque=lectus&eget=pellentesque&nunc=at&donec=nulla&quis=suspendisse&orci=potenti&eget=cras&orci=in&vehicula=purus', 'http://dummyimage.com/127x100.png/5fa2dd/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Legal Assistant', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('appl', 'pu6WlkIrv', 'Mante, Rippin and Nikolaus', 'Georgia', 951, 'eu nibh quisque id justo', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'https://netlog.com/duis/at/velit.png?habitasse=dolor&platea=sit&dictumst=amet&maecenas=consectetuer&ut=adipiscing&massa=elit&quis=proin&augue=interdum&luctus=mauris&tincidunt=non&nulla=ligula&mollis=pellentesque&molestie=ultrices&lorem=phasellus&quisque=id&ut=sapien&erat=in&curabitur=sapien&gravida=iaculis&nisi=congue&at=vivamus&nibh=metus&in=arcu&hac=adipiscing&habitasse=molestie&platea=hendrerit&dictumst=at&aliquam=vulputate&augue=vitae&quam=nisl&sollicitudin=aenean&vitae=lectus&consectetuer=pellentesque&eget=eget&rutrum=nunc&at=donec&lorem=quis&integer=orci&tincidunt=eget&ante=orci&vel=vehicula&ipsum=condimentum&praesent=curabitur&blandit=in&lacinia=libero&erat=ut&vestibulum=massa&sed=volutpat&magna=convallis&at=morbi&nunc=odio&commodo=odio&placerat=elementum&praesent=eu&blandit=interdum&nam=eu&nulla=tincidunt&integer=in&pede=leo&justo=maecenas&lacinia=pulvinar&eget=lobortis&tincidunt=est&eget=phasellus&tempus=sit&vel=amet&pede=erat&morbi=nulla&porttitor=tempus&lorem=vivamus&id=in&ligula=felis&suspendisse=eu&ornare=sapien&consequat=cursus&lectus=vestibulum&in=proin&est=eu&risus=mi&auctor=nulla&sed=ac&tristique=enim&in=in&tempus=tempor&sit=turpis&amet=nec&sem=euismod', 'http://dummyimage.com/194x100.png/ff4444/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Structural Engineer', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('ormp', 'LmcXu8ltep', 'Sanford-Crona', 'Texas', 526, 'augue vestibulum ante ipsum', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'http://alibaba.com/semper/est/quam/pharetra/magna/ac.html?dolor=fermentum&quis=donec&odio=ut&consequat=mauris&varius=eget&integer=massa&ac=tempor&leo=convallis&pellentesque=nulla&ultrices=neque&mattis=libero&odio=convallis&donec=eget&vitae=eleifend&nisi=luctus&nam=ultricies&ultrices=eu&libero=nibh&non=quisque&mattis=id', 'http://dummyimage.com/144x100.png/dddddd/000000', 'http://dummyimage.com/x.png/cc0000/ffffff', 'Account Representative I', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('grow', 'g0xXQ7b0RHS', 'Barton-Barton', 'New York', 703, 'leo maecenas pulvinar lobortis est', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://telegraph.co.uk/nulla.json?lorem=in&ipsum=sapien&dolor=iaculis&sit=congue&amet=vivamus&consectetuer=metus&adipiscing=arcu&elit=adipiscing&proin=molestie&risus=hendrerit&praesent=at&lectus=vulputate&vestibulum=vitae&quam=nisl&sapien=aenean&varius=lectus&ut=pellentesque&blandit=eget&non=nunc&interdum=donec&in=quis&ante=orci&vestibulum=eget&ante=orci&ipsum=vehicula&primis=condimentum&in=curabitur&faucibus=in&orci=libero&luctus=ut&et=massa&ultrices=volutpat&posuere=convallis&cubilia=morbi&curae=odio&duis=odio', 'http://dummyimage.com/162x100.png/5fa2dd/ffffff', 'http://dummyimage.com/x.png/cc0000/ffffff', 'Graphic Designer', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('cinb', 'mtwYDRjRIeKd', 'Hagenes-Tromp', 'Georgia', 718, 'phasellus in felis donec', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'https://webs.com/elit/sodales/scelerisque.xml?mi=quisque&pede=ut&malesuada=erat&in=curabitur&imperdiet=gravida&et=nisi&commodo=at&vulputate=nibh&justo=in&in=hac&blandit=habitasse&ultrices=platea&enim=dictumst&lorem=aliquam&ipsum=augue&dolor=quam&sit=sollicitudin&amet=vitae&consectetuer=consectetuer&adipiscing=eget&elit=rutrum&proin=at&interdum=lorem&mauris=integer&non=tincidunt&ligula=ante&pellentesque=vel&ultrices=ipsum&phasellus=praesent&id=blandit&sapien=lacinia&in=erat&sapien=vestibulum&iaculis=sed&congue=magna&vivamus=at&metus=nunc&arcu=commodo&adipiscing=placerat&molestie=praesent&hendrerit=blandit&at=nam&vulputate=nulla&vitae=integer&nisl=pede&aenean=justo&lectus=lacinia&pellentesque=eget&eget=tincidunt&nunc=eget&donec=tempus&quis=vel&orci=pede&eget=morbi&orci=porttitor&vehicula=lorem&condimentum=id&curabitur=ligula&in=suspendisse&libero=ornare&ut=consequat&massa=lectus&volutpat=in&convallis=est&morbi=risus&odio=auctor&odio=sed&elementum=tristique&eu=in&interdum=tempus&eu=sit&tincidunt=amet', 'http://dummyimage.com/160x100.png/cc0000/ffffff', 'http://dummyimage.com/x.png/5fa2dd/ffffff', 'Account Coordinator', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('zayo', 'hthVRI9LqaD', 'Yost Inc', 'Louisiana', 521, 'amet cursus id turpis integer', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'https://delicious.com/at/nibh/in.js?pede=justo&ullamcorper=nec&augue=condimentum&a=neque&suscipit=sapien&nulla=placerat&elit=ante&ac=nulla&nulla=justo&sed=aliquam&vel=quis&enim=turpis&sit=eget&amet=elit&nunc=sodales&viverra=scelerisque&dapibus=mauris&nulla=sit&suscipit=amet&ligula=eros&in=suspendisse&lacus=accumsan&curabitur=tortor&at=quis&ipsum=turpis&ac=sed&tellus=ante&semper=vivamus&interdum=tortor&mauris=duis&ullamcorper=mattis&purus=egestas&sit=metus&amet=aenean&nulla=fermentum&quisque=donec&arcu=ut&libero=mauris&rutrum=eget&ac=massa&lobortis=tempor&vel=convallis&dapibus=nulla&at=neque&diam=libero', 'http://dummyimage.com/130x100.png/cc0000/ffffff', 'http://dummyimage.com/x.png/5fa2dd/ffffff', 'Speech Pathologist', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('bofi', 'KbNRSF9TbLhy', 'Rippin-Cormier', 'District of Columbia', 914, 'morbi odio odio elementum', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://theatlantic.com/at/nunc.html?sit=pede&amet=lobortis&sapien=ligula&dignissim=sit&vestibulum=amet&vestibulum=eleifend&ante=pede&ipsum=libero&primis=quis&in=orci&faucibus=nullam&orci=molestie&luctus=nibh&et=in&ultrices=lectus&posuere=pellentesque&cubilia=at&curae=nulla&nulla=suspendisse&dapibus=potenti&dolor=cras&vel=in&est=purus&donec=eu&odio=magna&justo=vulputate&sollicitudin=luctus&ut=cum&suscipit=sociis&a=natoque&feugiat=penatibus&et=et&eros=magnis&vestibulum=dis&ac=parturient&est=montes&lacinia=nascetur&nisi=ridiculus&venenatis=mus&tristique=vivamus&fusce=vestibulum&congue=sagittis&diam=sapien&id=cum&ornare=sociis&imperdiet=natoque&sapien=penatibus&urna=et&pretium=magnis&nisl=dis&ut=parturient&volutpat=montes&sapien=nascetur&arcu=ridiculus&sed=mus&augue=etiam&aliquam=vel&erat=augue&volutpat=vestibulum&in=rutrum&congue=rutrum&etiam=neque&justo=aenean&etiam=auctor&pretium=gravida&iaculis=sem&justo=praesent&in=id&hac=massa&habitasse=id&platea=nisl', 'http://dummyimage.com/160x100.png/ff4444/ffffff', 'http://dummyimage.com/x.png/ff4444/ffffff', 'Internal Auditor', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('cohf', 'Z99S6zQ', 'Greenholt, Weimann and Greenfelder', 'New York', 507, 'mauris eget massa tempor', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'https://rambler.ru/nulla.js?nisl=lacus&nunc=at&rhoncus=velit&dui=vivamus&vel=vel&sem=nulla&sed=eget&sagittis=eros&nam=elementum&congue=pellentesque&risus=quisque&semper=porta&porta=volutpat&volutpat=erat&quam=quisque&pede=erat&lobortis=eros&ligula=viverra&sit=eget&amet=congue&eleifend=eget&pede=semper&libero=rutrum&quis=nulla&orci=nunc&nullam=purus&molestie=phasellus&nibh=in&in=felis&lectus=donec&pellentesque=semper&at=sapien&nulla=a&suspendisse=libero&potenti=nam&cras=dui&in=proin&purus=leo&eu=odio&magna=porttitor&vulputate=id&luctus=consequat&cum=in&sociis=consequat&natoque=ut&penatibus=nulla&et=sed&magnis=accumsan&dis=felis&parturient=ut&montes=at&nascetur=dolor&ridiculus=quis&mus=odio&vivamus=consequat&vestibulum=varius&sagittis=integer&sapien=ac&cum=leo&sociis=pellentesque&natoque=ultrices&penatibus=mattis&et=odio&magnis=donec&dis=vitae&parturient=nisi&montes=nam&nascetur=ultrices&ridiculus=libero&mus=non&etiam=mattis&vel=pulvinar&augue=nulla&vestibulum=pede&rutrum=ullamcorper&rutrum=augue&neque=a&aenean=suscipit&auctor=nulla&gravida=elit&sem=ac&praesent=nulla&id=sed&massa=vel&id=enim&nisl=sit&venenatis=amet&lacinia=nunc&aenean=viverra&sit=dapibus&amet=nulla&justo=suscipit&morbi=ligula&ut=in&odio=lacus&cras=curabitur&mi=at', 'http://dummyimage.com/123x100.png/ff4444/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Assistant Manager', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('hrtf', 'CHb8uwzzxrlm', 'Friesen LLC', 'District of Columbia', 185, 'morbi non lectus aliquam sit', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'http://topsy.com/odio/porttitor/id/consequat/in/consequat.jpg?fusce=mauris&consequat=viverra&nulla=diam&nisl=vitae&nunc=quam&nisl=suspendisse&duis=potenti&bibendum=nullam&felis=porttitor&sed=lacus&interdum=at&venenatis=turpis&turpis=donec&enim=posuere&blandit=metus&mi=vitae&in=ipsum&porttitor=aliquam&pede=non&justo=mauris&eu=morbi&massa=non&donec=lectus&dapibus=aliquam&duis=sit&at=amet&velit=diam&eu=in&est=magna&congue=bibendum&elementum=imperdiet&in=nullam&hac=orci&habitasse=pede&platea=venenatis&dictumst=non&morbi=sodales&vestibulum=sed&velit=tincidunt&id=eu&pretium=felis&iaculis=fusce&diam=posuere&erat=felis&fermentum=sed&justo=lacus&nec=morbi&condimentum=sem&neque=mauris&sapien=laoreet&placerat=ut&ante=rhoncus&nulla=aliquet&justo=pulvinar&aliquam=sed&quis=nisl&turpis=nunc&eget=rhoncus&elit=dui&sodales=vel&scelerisque=sem&mauris=sed&sit=sagittis&amet=nam&eros=congue&suspendisse=risus&accumsan=semper&tortor=porta&quis=volutpat&turpis=quam&sed=pede', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Safety Technician II', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('ucbi', 'MsqBZ72l', 'Quitzon-Walter', 'Ohio', 613, 'semper porta volutpat quam', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'https://dagondesign.com/ultrices/libero/non/mattis/pulvinar/nulla.html?id=enim&luctus=in&nec=tempor&molestie=turpis&sed=nec&justo=euismod&pellentesque=scelerisque&viverra=quam&pede=turpis&ac=adipiscing&diam=lorem&cras=vitae&pellentesque=mattis&volutpat=nibh&dui=ligula&maecenas=nec&tristique=sem&est=duis&et=aliquam&tempus=convallis&semper=nunc&est=proin&quam=at&pharetra=turpis&magna=a&ac=pede&consequat=posuere&metus=nonummy&sapien=integer&ut=non&nunc=velit&vestibulum=donec&ante=diam&ipsum=neque&primis=vestibulum&in=eget&faucibus=vulputate&orci=ut&luctus=ultrices&et=vel&ultrices=augue&posuere=vestibulum&cubilia=ante&curae=ipsum&mauris=primis&viverra=in&diam=faucibus&vitae=orci&quam=luctus&suspendisse=et&potenti=ultrices&nullam=posuere&porttitor=cubilia&lacus=curae&at=donec&turpis=pharetra&donec=magna&posuere=vestibulum&metus=aliquet&vitae=ultrices&ipsum=erat&aliquam=tortor&non=sollicitudin&mauris=mi&morbi=sit&non=amet&lectus=lobortis&aliquam=sapien&sit=sapien&amet=non&diam=mi&in=integer&magna=ac&bibendum=neque&imperdiet=duis&nullam=bibendum&orci=morbi&pede=non&venenatis=quam&non=nec&sodales=dui&sed=luctus&tincidunt=rutrum&eu=nulla&felis=tellus&fusce=in&posuere=sagittis&felis=dui&sed=vel&lacus=nisl&morbi=duis&sem=ac&mauris=nibh&laoreet=fusce&ut=lacus&rhoncus=purus&aliquet=aliquet&pulvinar=at&sed=feugiat&nisl=non', 'http://dummyimage.com/108x100.png/dddddd/000000', 'http://dummyimage.com/x.png/dddddd/000000', 'Administrative Officer', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('wsry', 'FqZTV5i', 'Lang-Hintz', 'Arizona', 956, 'mus vivamus vestibulum sagittis', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://boston.com/varius/integer/ac/leo/pellentesque.xml?erat=odio&quisque=elementum&erat=eu&eros=interdum&viverra=eu&eget=tincidunt&congue=in&eget=leo&semper=maecenas&rutrum=pulvinar&nulla=lobortis&nunc=est&purus=phasellus&phasellus=sit&in=amet&felis=erat&donec=nulla&semper=tempus&sapien=vivamus&a=in&libero=felis&nam=eu&dui=sapien&proin=cursus&leo=vestibulum&odio=proin&porttitor=eu&id=mi&consequat=nulla&in=ac&consequat=enim&ut=in&nulla=tempor&sed=turpis&accumsan=nec&felis=euismod&ut=scelerisque', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 'http://dummyimage.com/x.png/cc0000/ffffff', 'Senior Sales Associate', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('nmny', 'M4IWv22lG', 'Gleichner, Herzog and Nader', 'Washington', 751, 'purus eu magna vulputate', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'https://baidu.com/rhoncus/mauris/enim.xml?ut=fusce&massa=consequat&volutpat=nulla&convallis=nisl&morbi=nunc&odio=nisl&odio=duis&elementum=bibendum&eu=felis&interdum=sed&eu=interdum&tincidunt=venenatis&in=turpis&leo=enim&maecenas=blandit&pulvinar=mi&lobortis=in&est=porttitor&phasellus=pede&sit=justo&amet=eu&erat=massa&nulla=donec&tempus=dapibus', 'http://dummyimage.com/106x100.png/dddddd/000000', 'http://dummyimage.com/x.png/dddddd/000000', 'Editor', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('perf', 'XgZCn47B', 'Gislason, Halvorson and McDermott', 'Kentucky', 654, 'odio porttitor id consequat', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'https://technorati.com/ante/nulla/justo/aliquam/quis.html?metus=quam&aenean=turpis&fermentum=adipiscing&donec=lorem&ut=vitae&mauris=mattis&eget=nibh&massa=ligula&tempor=nec&convallis=sem&nulla=duis&neque=aliquam&libero=convallis&convallis=nunc&eget=proin&eleifend=at&luctus=turpis&ultricies=a&eu=pede&nibh=posuere&quisque=nonummy&id=integer&justo=non&sit=velit&amet=donec&sapien=diam&dignissim=neque&vestibulum=vestibulum&vestibulum=eget&ante=vulputate&ipsum=ut&primis=ultrices&in=vel&faucibus=augue&orci=vestibulum&luctus=ante&et=ipsum&ultrices=primis&posuere=in&cubilia=faucibus&curae=orci&nulla=luctus&dapibus=et&dolor=ultrices&vel=posuere&est=cubilia&donec=curae&odio=donec&justo=pharetra', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Marketing Manager', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('krpr', 'v7Cb0Lz4v', 'Effertz, Senger and Heathcote', 'District of Columbia', 656, 'aenean fermentum donec ut mauris', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'https://squarespace.com/sed/vestibulum/sit.js?ante=sed&ipsum=interdum&primis=venenatis&in=turpis&faucibus=enim&orci=blandit&luctus=mi&et=in&ultrices=porttitor&posuere=pede&cubilia=justo&curae=eu&mauris=massa&viverra=donec&diam=dapibus&vitae=duis&quam=at&suspendisse=velit&potenti=eu&nullam=est&porttitor=congue&lacus=elementum&at=in&turpis=hac&donec=habitasse&posuere=platea&metus=dictumst&vitae=morbi&ipsum=vestibulum&aliquam=velit&non=id&mauris=pretium&morbi=iaculis&non=diam&lectus=erat&aliquam=fermentum&sit=justo&amet=nec&diam=condimentum&in=neque&magna=sapien&bibendum=placerat&imperdiet=ante&nullam=nulla&orci=justo&pede=aliquam&venenatis=quis&non=turpis&sodales=eget&sed=elit', 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', 'http://dummyimage.com/x.png/cc0000/ffffff', 'Project Manager', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('carb', '1W4G6xsiiI2J', 'Moen-D''Amore', 'Illinois', 558, 'ante vestibulum ante ipsum primis', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'https://merriam-webster.com/quam/suspendisse/potenti.xml?turpis=mauris&integer=laoreet&aliquet=ut&massa=rhoncus&id=aliquet&lobortis=pulvinar&convallis=sed&tortor=nisl&risus=nunc&dapibus=rhoncus&augue=dui&vel=vel&accumsan=sem&tellus=sed&nisi=sagittis&eu=nam&orci=congue&mauris=risus&lacinia=semper&sapien=porta&quis=volutpat&libero=quam&nullam=pede&sit=lobortis&amet=ligula&turpis=sit&elementum=amet&ligula=eleifend&vehicula=pede&consequat=libero&morbi=quis&a=orci&ipsum=nullam&integer=molestie&a=nibh&nibh=in&in=lectus&quis=pellentesque&justo=at&maecenas=nulla&rhoncus=suspendisse&aliquam=potenti&lacus=cras&morbi=in&quis=purus&tortor=eu&id=magna&nulla=vulputate&ultrices=luctus&aliquet=cum&maecenas=sociis&leo=natoque&odio=penatibus&condimentum=et&id=magnis&luctus=dis&nec=parturient&molestie=montes&sed=nascetur&justo=ridiculus&pellentesque=mus&viverra=vivamus&pede=vestibulum&ac=sagittis&diam=sapien&cras=cum&pellentesque=sociis&volutpat=natoque&dui=penatibus&maecenas=et&tristique=magnis&est=dis&et=parturient&tempus=montes&semper=nascetur&est=ridiculus&quam=mus&pharetra=etiam&magna=vel&ac=augue', 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'http://dummyimage.com/x.png/ff4444/ffffff', 'Design Engineer', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('bidu', 'zUV9ZVW', 'Friesen, Abbott and Treutel', 'District of Columbia', 640, 'varius integer ac leo', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'https://themeforest.net/elementum.js?suspendisse=nulla&accumsan=integer&tortor=pede&quis=justo&turpis=lacinia&sed=eget&ante=tincidunt&vivamus=eget&tortor=tempus&duis=vel&mattis=pede&egestas=morbi&metus=porttitor&aenean=lorem&fermentum=id&donec=ligula', 'http://dummyimage.com/247x100.png/cc0000/ffffff', 'http://dummyimage.com/x.png/dddddd/000000', 'Tax Accountant', 'company');
insert into companies (company_handle, password, company_name, state, num_employees, short_description, long_description, website_url, logo_url, main_image_url, looking_for, role) values ('acco', 'frLn0MBkh', 'Rutherford, Morissette and Ratke', 'Oklahoma', 109, 'pellentesque eget nunc donec quis', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'https://princeton.edu/sed/vel/enim/sit/amet/nunc.png?quam=posuere&sapien=metus&varius=vitae&ut=ipsum&blandit=aliquam&non=non&interdum=mauris&in=morbi&ante=non&vestibulum=lectus&ante=aliquam&ipsum=sit&primis=amet&in=diam&faucibus=in&orci=magna&luctus=bibendum&et=imperdiet&ultrices=nullam&posuere=orci&cubilia=pede&curae=venenatis', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'http://dummyimage.com/x.png/cc0000/ffffff', 'Quality Control Specialist', 'company');